// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"greeter/conf"
	"greeter/internal/biz"
	"greeter/internal/data"
	"greeter/internal/server"
	"greeter/internal/service"
	"greeter/pkg/logger"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func InitApp() *App {
	confConf := conf.NewConf()
	zapLogger := logger.NewZapLogger()
	dataData := data.NewData(confConf, zapLogger)
	greeterRepo := data.NewGreeterRepo(dataData, zapLogger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, zapLogger)
	greeterService := service.NewGreeterService(greeterUsecase)
	httpServer := server.NewHTTPServer(confConf, greeterService, zapLogger)
	grpcServer := server.NewGRPCServer(confConf, greeterService, zapLogger)
	app := &App{
		Http: httpServer,
		Grpc: grpcServer,
	}
	return app
}
